name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login --username $DOCKER_USER --password $DOCKER_PASSWORD
    
    - name: Build the Docker image
      run: make build
    
    - name: Docker Publish
      run: make publish
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
